# Generated by Django 2.1.5 on 2019-02-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0002_auto_20190204_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='time_range',
        ),
    ]
