# Generated by Django 2.1.5 on 2019-02-05 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0004_alert_time_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
